### ISSUE TITLE
Revision de toutes les vues

### ISSUE THREAD

**Issue by houchker** [eurojulien/LOG660-TP2#10]
Révision de toutes les vues afin de vérifier est qu'il sont bient faites, surtout les noms des zones de text et bontons et labels

**Comment by domleo** [comment]
Les accents ne load pas bien pour moi....

**Comment by domleo** [comment]
je pense qu'il manque une vue,  Vue qui affiche les location presentement choisi.

**Comment by houchker** [comment]
Done
